# Generated by Django 4.1.2 on 2022-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='Latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
    ]
