# Generated by Django 4.0 on 2022-11-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
    ]
