# Generated by Django 4.1.2 on 2022-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_alter_store_address_alter_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
