# Generated by Django 4.1.2 on 2022-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0003_alter_store_address_alter_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Address',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
    ]
