# Generated by Django 4.1.2 on 2022-10-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_alter_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Address',
            field=models.TextField(blank=True, max_length=258, null=True),
        ),
    ]
