# Generated by Django 4.1.2 on 2022-10-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_rename_address_store_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Store_Address',
        ),
        migrations.AddField(
            model_name='store',
            name='Store Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
