# Generated by Django 4.1.2 on 2022-10-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_remove_store_store_address_store_store address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Store Address',
            new_name='Store_Address',
        ),
    ]
