# Generated by Django 4.1.2 on 2022-10-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0008_rename_store address_store_store_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Store_Address',
            new_name='store_address',
        ),
    ]
