# Generated by Django 4.1.2 on 2022-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0009_rename_store_address_store_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Longitude',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.TextField(blank=True, null=True, verbose_name='Store Address'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitude'),
        ),
    ]
