# Generated by Django 4.1.2 on 2022-10-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stores',
            new_name='store',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('store', 'name')},
        ),
    ]
