# Generated by Django 4.1.2 on 2022-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0013_rename_stores_item_store_alter_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Active', max_length=10),
        ),
    ]
