# Generated by Django 4.1.2 on 2022-10-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0014_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
