# Generated by Django 4.1.2 on 2022-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0015_rename_item_order_items_remove_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='foodordering.item'),
        ),
    ]
