# Generated by Django 4.1.2 on 2022-10-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0016_alter_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='merchant',
        ),
    ]
